version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/LibraMusic/LibraCore"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "ruff"
