version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/LibraMusic/backend"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"