# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

env:
  - '{{ if not (isEnvSet "NIGHTLY_TAG") }}NIGHTLY_TAG=v0.1.0-nightly{{ end }}'
  - SHORT_PROJECT_NAME=libra

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

report_sizes: true

git:
  ignore_tags:
    - '{{ if not (isEnvSet "IS_NIGHTLY_BUILD") }}{{ .Env.NIGHTLY_TAG }}{{ end }}'

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - main: ./cmd/libra
    binary: libra
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/libramusic/libracore.rawVersion={{ if isEnvSet "IS_NIGHTLY_BUILD" }}{{ .RawVersion }}-DEV{{ else }}{{ .Version }}{{ end }}

dockers_v2:
  - images:
      - "devreaper0/libracore"
      - "ghcr.io/libramusic/libracore"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - '{{ if isEnvSet "IS_NIGHTLY_BUILD" }}nightly{{ else }}latest{{ end }}'
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "A new, open, and extensible music service"
      "org.opencontainers.image.url": "{{ .GitURL }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.version": "{{ .Tag }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Env.SHORT_PROJECT_NAME }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

nfpms:
  - package_name: libra
    vendor: LibraMusic
    maintainer: DevReaper0 <devreaper0@gmail.com>
    description: A new, open, and extensible music service
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - ffmpeg
    contents:
      - src: ./completions/libra.bash
        dst: /usr/share/bash-completion/completions/libra
        file_info:
          mode: 0644
      - src: ./completions/libra.fish
        dst: /usr/share/fish/vendor_completions.d/libra.fish
        file_info:
          mode: 0644
      - src: ./completions/libra.zsh
        dst: /usr/share/zsh/vendor-completions/_libra
        file_info:
          mode: 0644
      - src: ./manpages/libra.1.gz
        dst: /usr/share/man/man1/libra.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/libra/copyright
        file_info:
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

universal_binaries:
  - name_template: "{{ .Env.SHORT_PROJECT_NAME }}"

upx:
  - enabled: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  github:
    owner: LibraMusic
    name: LibraCore
  prerelease: auto
