name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Install dependencies
      run: make dep

    - name: Build
      run: make build

    - name: Run tests
      run: make test_coverage

    - name: Report test coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: go
        coverage-file: cover.out
        dsn: ${{ secrets.DEEPSOURCE_DSN }}

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: libra
        path: libra
